DROP TABLE IF EXISTS POST;

CREATE TABLE IF NOT EXISTS POST (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    CONTENT VARCHAR(255),
    CREATE_AT TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP
);